#!/bin/sh

clear

### Check for errors; abandon the process if error exist
function checkError {
    if [[ $1 != 0 ]] ; then
        #prevent commit with error code
        exit 99
    fi
}

echo "*** Checking JavaScript for lint... ***"

#run LintRunner
node hooks/pre-commit.js

checkError $?


### Exit successfully
exit 0
