#!/bin/sh

clear

### Check for errors; abandon the process if error exist
function checkError {
    if [[ $1 != 0 ]] ; then
        #prevent commit with error code
        exit 99
    fi
}

echo "*** Checking code for lint... ***"
node hooks/check-lint.js
checkError $?

echo "*** Running Jasmine Tests... ***"
node tests/specs.js
checkError $?

### Exit successfully
exit 0
